# Generated by Django 3.2 on 2022-11-07 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
                ('content', models.TextField(max_length=6000)),
                ('source', models.CharField(max_length=255)),
                ('forward_link', models.URLField(max_length=1000)),
                ('news_cat', models.CharField(choices=[('TCH', 'Technology'), ('SPR', 'Sports'), ('BSN', 'Business'), ('ENT', 'Entertainment'), ('POL', 'Politics'), ('OTHR', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='news_cron',
            fields=[
                ('news_cron1', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fetched_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
